#!/usr/bin/env bash
set -euo pipefail

: "${MEND_SCA_SCAN_DIR:?MEND_SCA_SCAN_DIR must be set by the Controller}"

npmrc="${MEND_SCA_SCAN_DIR}/.npmrc"
echo "[npm/pre-build] writing project .npmrc -> ${npmrc}"

cat > "${npmrc}" <<'EOF'
# Generated by mend-hooks-customization-repo (common pre-build)
# Point @my-scope at a private registry; auth token must be provided
# via the host-rules step that runs before this hook.
@my-scope:registry=https://npm.internal.example.com/
//npm.internal.example.com/:_authToken=${NPM_INTERNAL_TOKEN}
always-auth=true
EOF